version: '2'
services:
    jhipsterweb-app:
        image: jhipsterweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterweb-postgresql:5432/jhipsterweb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterweb-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterweb-postgresql
